# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_red/indicate_2_red.xci
# IP: The module: 'indicate_2_red' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_red/indicate_2_red_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'indicate_2_red'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_red/indicate_2_red.xci
# IP: The module: 'indicate_2_red' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_red/indicate_2_red_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'indicate_2_red'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
