# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/background_red/background_red.xci
# IP: The module: 'background_red' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/background_red/background_red_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background_red'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/background_red/background_red.xci
# IP: The module: 'background_red' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/background_red/background_red_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'background_red'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
