# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.cache/wt} [current_project]
set_property parent.project_path {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/name_RED.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/name_GREEN.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/name_BLUE.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/proyecto_movimiento/large_RED.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/proyecto_movimiento/large_GREEN.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/proyecto_movimiento/large_BLUE.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/debes_igualar_RED.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/debes_igualar_GREEN.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/debes_igualar_BLUE.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/tu_color_RED.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/tu_color_GREEN.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/tu_color_BLUE.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/flecha_RED.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/flecha_GREEN.coe
add_files /home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/flecha_BLUE.coe
read_vhdl -library xil_defaultlib {
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/ALU.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Adder16.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/AdderDataIn.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/CPU.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/CU.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Clock_Divider.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Debouncer.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Display_Controller.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/FA.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/GTX1050.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/HA.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Multiplexor.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/MuxAddrs.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/MuxData.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/MuxPC.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Programmer.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/RAM.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/ROM.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Reg.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/RegContPC.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/RegSP.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/RegStatus.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Timer.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/UART.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/demuxOUTPUT.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/demux_advinanzas.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/indicate_1_rom.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/indicate_2_rom.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/logo_rom.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/muxINPUT.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/name_rom.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/pointer_rom.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/reg_adivinanzas.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/vga_sync.vhd}
  {/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/new/Basys3.vhd}
}
read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/name_red/name_red.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/name_red/name_red_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/name_green/name_green.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/name_green/name_green_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/name_blue/name_blue.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/name_blue/name_blue_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/logo_red/logo_red.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/logo_red/logo_red_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/logo_green/logo_green.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/logo_green/logo_green_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/logo_blue/logo_blue.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/logo_blue/logo_blue_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_1_red/indicate_1_red.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_1_red/indicate_1_red_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_1_green/indicate_1_green.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_1_green/indicate_1_green_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicator_1_blue/indicator_1_blue.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicator_1_blue/indicator_1_blue_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_red/indicate_2_red.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_red/indicate_2_red_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_green/indicate_2_green.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_green/indicate_2_green_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_blue/indicate_2_blue.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/indicate_2_blue/indicate_2_blue_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/pointer_red/pointer_red.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/pointer_red/pointer_red_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/pointer_green/pointer_green.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/pointer_green/pointer_green_ooc.xdc}}]

read_ip -quiet {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/pointer_blue/pointer_blue.xci}}
set_property used_in_implementation false [get_files -all {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/sources_1/ip/pointer_blue/pointer_blue_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}
set_property used_in_implementation false [get_files {{/home/claudio/U/24.2/arqui/g21/Entrega-3/especial_fase_2_0/Proyecto Base.srcs/constrs_1/new/Basys3.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Basys3 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Basys3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Basys3_utilization_synth.rpt -pb Basys3_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
