# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/claudio/U/24.2/arqui/g21/Tower-Blox/architecture/architecture_stable.srcs/sources_1/ip/yellow_block_green/yellow_block_green.xci
# IP: The module: 'yellow_block_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Tower-Blox/architecture/architecture_stable.srcs/sources_1/ip/yellow_block_green/yellow_block_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'yellow_block_green'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/claudio/U/24.2/arqui/g21/Tower-Blox/architecture/architecture_stable.srcs/sources_1/ip/yellow_block_green/yellow_block_green.xci
# IP: The module: 'yellow_block_green' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Tower-Blox/architecture/architecture_stable.srcs/sources_1/ip/yellow_block_green/yellow_block_green_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'yellow_block_green'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
