# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/nave_azul_blue/nave_azul_blue.xci
# IP: The module: 'nave_azul_blue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/nave_azul_blue/nave_azul_blue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nave_azul_blue'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/nave_azul_blue/nave_azul_blue.xci
# IP: The module: 'nave_azul_blue' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/claudio/U/24.2/arqui/g21/Su-invaders/architecture/architecture_stable.srcs/sources_1/ip/nave_azul_blue/nave_azul_blue_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nave_azul_blue'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
